### ISSUE TITLE
Error MSB3202 .. AspNet5DemoApp.xproj.metaproj not found

### ISSUE THREAD

**Issue by rollsch** [jincod/AspNet5DemoApp#3]
I tried deploying a completely unchanged version of this project to heroku and I get the following error upon deploying.

There is no metaproj file and I'm not sure if the build script is trying to create one and failing? What should this file contain? I don't understand the build process well enough to debug this further,.

Any help would be much appreciated.

remote: /tmp/build_bb0646bd8303182f6bd73ce264103dff/dotnet/sdk/1.0.0-preview5-00
4232/NuGet.targets(164,5): error MSB3202: The project file "/tmp/build_bb0646bd8
303182f6bd73ce264103dff/src/AspNet5DemoApp/AspNet5DemoApp.xproj.metaproj" was no
t found. [/tmp/build_bb0646bd8303182f6bd73ce264103dff/AspNet5DemoApp.sln]
remote:  !     Push rejected, failed to compile ASP.NET Core app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to ****.
remote:

Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as C
onsolas!
To https://git.heroku.com/****.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/****.git'

**Comment by jincod** [comment]
@rolandh is It still actual? Can I help you?

**Comment by rollsch** [comment]
Too long ago. I no longer am testing out heroku but thank you for the reply.
