### ISSUE TITLE
Can't deploying on Heroku due to some error.

### ISSUE THREAD

**Issue by hbbhaumikpatel** [jincod/AspNet5DemoApp#4]
I have API project and I try to publish on Heroku.
While I push on Heroku I got an error. The full build log file attached.
[Build Log.txt](https://github.com/jincod/AspNet5DemoApp/files/1253578/Build.Log.txt)

> dotnet/sdk/NuGetFallbackFolder/microsoft.identitymodel.clients.activedirectory/3.14.1/src/src/ADAL.PCL.Android/Resources/Resource.Designer.cs(12,20): error CS0400: The type or namespace name 'Android' could not be found in the global namespace (are you missing an assembly reference?) [/tmp/build_54bd10f2a99affeb41ea501751ae3a17/WebAPIApplication.csproj]
> 
>  !     Push rejected, failed to compile ASP.NET Core app.
>  !     Push failed

```
dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by jincod** [comment]
Hi @hbbhaumikpatel 

Thank you for feedback.

`Microsoft.IdentityModel.Clients.ActiveDirectory` is client package and should be exclude from API dependencies. I think this issue not connected this heroku

**Comment by hbbhaumikpatel** [comment]
Hi 

Well, I have not added any kind of this type of package.
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>
  <Target Name="PrePublishTarget" BeforeTargets="PrepareForPublish">
    <Exec Command="npm run build" />
    <ItemGroup>
      <_GeneratedFiles Include="$(GeneratedItemPatterns)" />
      <ContentWithTargetPath Include="@(_GeneratedFiles->'%(FullPath)')" RelativePath="%(_GeneratedFiles.Identity)" TargetPath="%(_GeneratedFiles.Identity)" CopyToPublishDirectory="PreserveNewest" />
      <Dist Include="../../build/**" />
    </ItemGroup>
    <Copy SourceFiles="@(Dist)" DestinationFolder="$(PublishDir)\wwwroot\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
```
If you want to project I can share with you. Let me know.

**Comment by jincod** [comment]
Hi @hbbhaumikpatel 

Yes, could you please share your project. I'll try to help you.

**Comment by hbbhaumikpatel** [comment]
Can You please share your email? , So I can invite direct on Heroku.

**Comment by jincod** [comment]
Could please share this repo on github? 

After you can easy connect github repo to heroku (on Deploy tab)![image](https://user-images.githubusercontent.com/1294432/29871342-da84fe90-8da4-11e7-884f-c61bd854c4fc.png)

**Comment by hbbhaumikpatel** [comment]
[WebAPIApplication.zip](https://github.com/jincod/AspNet5DemoApp/files/1263468/WebAPIApplication.zip)

I uploaded simple api project.

**Comment by jincod** [comment]
ok, i'll investigate and back to you!

**Comment by anderslm** [comment]
It appears that this only happens when not using a solution file. If one sets up a solution file and adds the web api project to the solution, then heroku will deploy it successfully

**Comment by hbbhaumikpatel** [comment]
I do same way the error was gone. But deploy failed.
[Updated_Code.zip](https://github.com/jincod/AspNet5DemoApp/files/1266790/Updated_Code.zip)
[build_log.txt](https://github.com/jincod/AspNet5DemoApp/files/1266791/build_log.txt)

```
/bin/sh: 2: /tmp/tmpb3bfcfc3065b46e2bf06241a4446e466.exec.cmd: npm: not found
/tmp/build_9b0dd6f8bc4e50226ba7ffb35cb46537/WebAPIApplication/WebAPIApplication.csproj(19,5): error MSB3073: The command "npm run build" exited with code 127.
```

Project directory structure and also I uploaded project.
![image](https://user-images.githubusercontent.com/10570010/29919777-54cbe650-8e68-11e7-9b4f-14c27ef26f99.png)

**Comment by jincod** [comment]
@hbbhaumikpatel 

You should add nodejs buildpack 
![image](https://user-images.githubusercontent.com/1294432/29920365-a4326090-8e66-11e7-8f8b-159704ad84f4.png)

**Comment by hbbhaumikpatel** [comment]
I added build pack.
```
heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack
heroku buildpacks:add --index 1 heroku/nodejs
```
My `package.json` looks like below.
```
{
  "name": "aspnet-core-demo-app",
  "version": "0.0.1",
  "private": true,
  "description": "Demo app",
  "repository": {
    "type": "git",
    "url": "https://git.heroku.com/dotnetcorenew.git"
  },
  "dependencies": {
  },
  "scripts": {
    
  }
}
```
Still given error.
```
npm ERR! Linux 3.13.0-128-generic
remote:   npm ERR! argv "/tmp/build_a48049e05a969ac305b0b2aa736598de/.heroku/node/bin/node" "/tmp/build_a48049e05a969ac305b0
b2aa736598de/.heroku/node/bin/npm" "run" "build"
remote:   npm ERR! node v6.11.2
remote:   npm ERR! npm  v3.10.10
```
Some thing I missing in  `package.json`?

**Comment by jincod** [comment]
Yes, `npm run build` expects
```json
"scripts": {
  "build": "something actions"
}
```

If you doesn't need node.js support, just remove `Target` https://github.com/jincod/AspNet5DemoApp/blob/ac25ccd96bae65703aac9d459d66c50fd5eccb30/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj#L25 and node.js buildpack from heroku

**Comment by hbbhaumikpatel** [comment]
**Thanks for your great support.**

I don't want to node so I removed `<Target Name="PrePublishTarget" BeforeTargets="PrepareForPublish"> `  and it's working fine.

**Comment by hbbhaumikpatel** [comment]
I have one question for you Why we need Solution File (.sln)? Without solution file can we deploy?

**Comment by jincod** [comment]
Grade!

I'm investigating problem with sln file. I'll notify you, if get more information about this.

Shall I close issue?

**Comment by hbbhaumikpatel** [comment]
Yes. Sure.

**Comment by jincod** [comment]
Hi @hbbhaumikpatel

I've updated buildpack: changed dotnet installation path (https://github.com/jincod/dotnetcore-buildpack/commit/f09e5e785d022261769020177d095df7c29ae003). Could you please test it?

P.S.: sln file not required

**Comment by hbbhaumikpatel** [comment]
Yes, I removed .sln file and re-deploy. It's working good. Thanks.

One more thing I notice that my slug size full. As you know my project size only 1.75MB. and I have only one master branch.

Many time I deploy that's why?
Even I try [heroku-repo](https://github.com/heroku/heroku-repo) and execute below command.
```
heroku plugins:install heroku-repo
heroku repo:gc --app appname
heroku repo:purge_cache --app appname
```
![image](https://user-images.githubusercontent.com/10570010/29958641-5a4e26e8-8f11-11e7-85e2-547bb741ecec.png)

**Comment by jincod** [comment]
I've create issue for this (https://github.com/jincod/dotnetcore-buildpack/issues/19)
