### ISSUE TITLE
HTTPS redirect

### ISSUE THREAD

**Issue by changhuixu** [jincod/AspNet5DemoApp#6]
Hi, 
https://github.com/jincod/AspNetCoreDemoApp/blob/master/src/AspNetCoreDemoApp/Startup.cs#L36-L41
it seems not working for the following links
http://aspnetcoredemoapp.herokuapp.com/
http://aspnetcoredemoapp.herokuapp.com/api/values

Any ideas? Thank you.

**Comment by jincod** [comment]
Hi @changhuixu,

I can't reproduce it. Could you please give me more info?

**Comment by changhuixu** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/KGWqpxf/2019-10-31-08-21-50-aspnetcoredemoapp-herokuapp-com-api-values.png" alt="2019-10-31-08-21-50-aspnetcoredemoapp-herokuapp-com-api-values" border="0"></a>

If using http url, the address won't redirect to https

**Comment by jincod** [comment]
Hi @changhuixu 

It should work now, I've updated buildpack as well

**Comment by changhuixu** [comment]
Yes, it works now. Thank you.
Another question, is there any reason that you added `app.UserForwardedHeaders()`?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.0

**Comment by jincod** [comment]
Yes, `UserForwardedHeaders()` needs for `UseHttpsRedirection()`. Heroku use proxy in front of app (reverse proxy scenario)

**Comment by changhuixu** [comment]
Thank you for your explanations.
BTW: `IS_HEROKU` is not needed.
I used `DYNO` to make it work. https://github.com/changhuixu/dotnetlabs/blob/master/ASPNetCoreLabs/HerokuContainer/Colors.API/Startup.cs#L67

**Comment by jincod** [comment]
Have you set `DYNO` yourself or is it set by Heroku?

**Comment by changhuixu** [comment]
It is set by Heroku. I recommend you also use it, so that your buildpack doesn't need an extra step to set the environment variable.

**Comment by jincod** [comment]
Here more about `Dyno` https://devcenter.heroku.com/articles/dynos#local-environment-variables

Thank you
