### ISSUE TITLE
Setup with multiple projects

### ISSUE THREAD

**Issue by kristof12345** [jincod/AspNet5DemoApp#7]
Hi!

Could you give a more detailed description about setting the startup project with environment variables?

Great work! Thanks for the answer in advance.

**Comment by jincod** [comment]
Hello @kristof12345,

You need to set the environment variables https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard and inject `IConfiguration` to your service or controller.

Here more info about configuration in ASP.NET Core https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables

**Comment by jincod** [comment]
Hello @kristof12345,

You need to set `PROJECT_FILE` environment variable for required project file, for example `./src/Web/Web.csproj`

**Comment by kristof12345** [comment]
Thank you! It works fine.
